# Generated by Django 3.0.6 on 2020-07-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashierprofile',
            name='user',
        ),
    ]
