# Generated by Django 3.0.6 on 2020-05-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierprofile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
