# Generated by Django 3.0.6 on 2020-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_stored',
            field=models.BooleanField(default=True),
        ),
    ]
