# Generated by Django 3.0.6 on 2020-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemcounter',
            name='custom_instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
