# Generated by Django 3.0.6 on 2020-06-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='receipt_html',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
