# Generated by Django 3.0.6 on 2020-09-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_cost_stored',
        ),
    ]
