# Generated by Django 3.0.6 on 2020-06-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0005_auto_20200621_1923'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemcounter',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant_admin.AddOnItem'),
            preserve_default=False,
        ),
    ]
