# Generated by Django 3.0.6 on 2020-06-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='custom_tip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitemcounter',
            name='custom_instructions',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
