# Generated by Django 3.0.6 on 2020-09-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='cart',
            name='handle_cash',
            field=models.BooleanField(null=True),
        ),
    ]
