# Generated by Django 3.0.6 on 2020-07-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0006_restaurant_language'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemcounter',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant_admin.Restaurant'),
            preserve_default=False,
        ),
    ]
