# Generated by Django 3.0.6 on 2020-06-23 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_addongroup_restaurant'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemcounter',
            name='addon_items',
            field=models.ManyToManyField(blank=True, to='restaurant_admin.AddOnItem'),
        ),
        migrations.AlterField(
            model_name='menuitemcounter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
