# Generated by Django 3.0.6 on 2020-09-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_card_stored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_stored',
            field=models.BooleanField(default=False),
        ),
    ]
