# Generated by Django 3.0.6 on 2020-09-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cart_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='processed',
        ),
    ]
