# Generated by Django 3.0.6 on 2020-06-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cart_receipt_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='receipt_html',
            field=models.TextField(null=True),
        ),
    ]
