# Generated by Django 3.0.6 on 2020-05-27 01:35

from django.db import migrations, models
import django.utils.timezone as timezone

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cart_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='stripe_order_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
