# Generated by Django 3.0.6 on 2020-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cart_receipt_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
