# Generated by Django 3.0.6 on 2020-06-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0005_auto_20200621_1923'),
        ('customers', '0003_auto_20200622_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemcounter',
            name='addon',
        ),
        migrations.AddField(
            model_name='menuitemcounter',
            name='addon_items',
            field=models.ManyToManyField(to='restaurant_admin.AddOnItem'),
        ),
    ]
