# Generated by Django 3.0.6 on 2020-09-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_cart_shipping_cost_stored'),
        ('customers', '0003_remove_cart_processed'),
    ]

    operations = [
    ]
