# Generated by Django 3.0.6 on 2020-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_cart_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_cost_stored',
            field=models.BooleanField(default=False),
        ),
    ]
