# Generated by Django 3.0.6 on 2020-06-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0005_auto_20200621_1923'),
        ('customers', '0004_auto_20200622_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcounter',
            name='addon_items',
            field=models.ManyToManyField(blank=True, to='restaurant_admin.AddOnItem'),
        ),
    ]
