# Generated by Django 3.0.6 on 2020-06-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200531_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcounter',
            name='custom_instructions',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
