# Generated by Django 3.0.6 on 2020-06-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200623_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcounter',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
