# Generated by Django 3.0.6 on 2020-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200602_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='custom_tip',
            field=models.BooleanField(default=False),
        ),
    ]
