# Generated by Django 3.0.6 on 2020-06-23 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20200623_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcounter',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
