# Generated by Django 3.0.6 on 2020-06-23 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20200623_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcounter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
