# Generated by Django 3.0.6 on 2020-09-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
