# Generated by Django 3.0.6 on 2020-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='answered_pay_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='handle_payment',
            field=models.BooleanField(null=True),
        ),
    ]
