# Generated by Django 3.0.6 on 2020-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='qr_code_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='info_input',
            field=models.BooleanField(default=False),
        ),
    ]
