# Generated by Django 3.0.6 on 2020-05-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
    ]
