# Generated by Django 3.0.6 on 2020-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
