# Generated by Django 3.0.6 on 2020-06-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menus',
            field=models.ManyToManyField(to='restaurant_admin.Menu'),
        ),
    ]
