# Generated by Django 3.0.6 on 2020-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='about',
            field=models.CharField(max_length=255, null=True, verbose_name="Your Restaurant's Vision"),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='info',
            field=models.CharField(max_length=255, null=True, verbose_name='Additional Info'),
        ),
    ]
