# Generated by Django 3.0.6 on 2020-06-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_remove_restaurant_dine_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dine_in',
            field=models.BooleanField(default=False),
        ),
    ]
