# Generated by Django 3.0.6 on 2020-05-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_menuitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuphoto',
            name='item',
        ),
        migrations.AddField(
            model_name='menu',
            name='photo_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='photo_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MenuCoverPhoto',
        ),
        migrations.DeleteModel(
            name='MenuPhoto',
        ),
    ]
