# Generated by Django 3.0.6 on 2020-05-27 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_auto_20200525_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='about',
            field=models.TextField(max_length=255, null=True, verbose_name="Your Restaurant's Vision"),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='info',
            field=models.TextField(max_length=255, null=True, verbose_name='Additional Info'),
        ),
    ]
