# Generated by Django 3.0.6 on 2020-06-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_restaurant_info_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='qr_code_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
