# Generated by Django 3.0.6 on 2020-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_selectoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='kitchen_login_no',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
