# Generated by Django 3.0.6 on 2020-05-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_auto_20200531_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='stripe_account_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
