# Generated by Django 3.0.6 on 2020-07-03 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0003_restaurant_dine_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='course',
            new_name='category',
        ),
    ]
