# Generated by Django 3.0.6 on 2020-09-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0003_auto_20200904_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='pickup_address',
        ),
    ]
