# Generated by Django 3.0.6 on 2020-09-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0004_remove_restaurant_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='offer_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
