# Generated by Django 3.0.6 on 2020-06-21 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0004_auto_20200620_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menus',
            field=models.ManyToManyField(to='restaurant_admin.Menu'),
        ),
        migrations.CreateModel(
            name='AddOnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_admin.AddOnGroup')),
            ],
        ),
        migrations.AddField(
            model_name='addongroup',
            name='menu_items',
            field=models.ManyToManyField(to='restaurant_admin.MenuItem'),
        ),
    ]
