# Generated by Django 3.0.6 on 2020-07-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0004_auto_20200703_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectoption',
            name='menu',
        ),
        migrations.AddField(
            model_name='selectoption',
            name='menus',
            field=models.ManyToManyField(to='restaurant_admin.Menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='', max_length=200, verbose_name='Category'),
        ),
    ]
