# Generated by Django 3.0.6 on 2020-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0004_auto_20200703_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='', max_length=200, verbose_name='Category'),
        ),
    ]
