# Generated by Django 3.0.6 on 2020-07-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0005_auto_20200703_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectoption',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_admin.Menu'),
        ),
    ]
