# Generated by Django 3.0.6 on 2020-09-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0005_auto_20200905_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemPhotoUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=255, null=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_admin.MenuItem')),
            ],
        ),
    ]
