# Generated by Django 3.0.6 on 2020-07-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0005_auto_20200706_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='language',
            field=models.CharField(default='en-us', max_length=10),
        ),
    ]
