# Generated by Django 3.0.6 on 2020-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0006_auto_20200703_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectoption',
            name='menu',
        ),
        migrations.AddField(
            model_name='selectoption',
            name='menus',
            field=models.ManyToManyField(to='restaurant_admin.Menu'),
        ),
    ]
